# Using Holidayiq Dataset

In [ ]:
import pandas as pd
import numpy as np
from sklearn.cluster import KMeans
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import davies_bouldin_score
from sklearn.metrics import silhouette_score

In [ ]:
data = pd.read_csv("/content/drive/MyDrive/Ensemble project/buddymove_holidayiq.csv")

In [ ]:
data.head(5)

User Id  Sports  Religious  Nature  Theatre  Shopping  Picnic
0  User 1       2         77      79       69        68      95
1  User 2       2         62      76       76        69      68
2  User 3       2         50      97       87        50      75
3  User 4       2         68      77       95        76      61
4  User 5       2         98      54       59        95      86

In [ ]:
X = np.array(data.drop(["User Id"], axis = 1))

In [ ]:
kmeans = KMeans(n_clusters = 3, random_state = 42)
l0 = kmeans.fit_predict(X).tolist()
print(l0)

[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 0, 2, 2, 2, 2, 2, 2, 0, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 2, 1, 1, 1, 1, 0, 1, 1, 1, 2, 1, 1, 0, 1, 1, 2, 0, 2, 1, 0, 2, 0, 1, 2, 0, 1, 1, 1, 1, 1, 1, 2, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 2, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1]


In [ ]:
X1 = np.array(data.drop(["User Id", "Sports", "Religious", "Nature"], axis = 1))
X2 = np.array(data.drop(["User Id", "Sports", "Religious", "Theatre"], axis = 1))
X3 = np.array(data.drop(["User Id", "Sports", "Religious", "Shopping"], axis = 1))
X4 = np.array(data.drop(["User Id", "Sports", "Religious", "Picnic"], axis = 1))
X5 = np.array(data.drop(["User Id", "Religious", "Nature", "Theatre"], axis = 1))
X6 = np.array(data.drop(["User Id", "Religious", "Nature", "Shopping"], axis = 1))
X7 = np.array(data.drop(["User Id", "Religious", "Nature", "Picnic"], axis = 1))
X8 = np.array(data.drop(["User Id", "Nature", "Theatre", "Shopping"], axis = 1))
X9 = np.array(data.drop(["User Id", "Nature", "Theatre", "Picnic"], axis = 1))
X10 = np.array(data.drop(["User Id", "Theatre", "Shopping", "Picnic"], axis = 1))

In [ ]:
kmeans = KMeans(n_clusters = 3, random_state = 42)
l1 = kmeans.fit_predict(X1).tolist()
print("l1 = " + str(l1))

l1 = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 2, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 2, 1, 1, 0, 0, 1, 1, 2, 1, 1, 0, 2, 1, 0, 2, 0, 2, 0, 1, 2, 1, 1, 1, 0, 1, 1, 0, 1, 0, 2, 1, 2, 2, 2, 0, 0, 2, 1, 1, 2, 1, 1, 1, 2, 1, 1, 2, 1, 2, 1, 2, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 2, 1, 2, 1, 1, 2, 1, 1, 2, 1, 2, 1, 1, 1, 1, 2, 1, 1, 2, 2, 2, 1, 2, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 2, 2, 1, 1, 1, 1, 2, 0, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 2]


In [ ]:
kmeans = KMeans(n_clusters = 3, random_state = 42)
l2 = kmeans.fit_predict(X2).tolist()
print("l2 = " + str(l2))

l2 = [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 1, 0, 2, 2, 0, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 1, 1, 1, 2, 0, 1, 1, 2, 1, 1, 1, 2, 2, 1, 2, 1, 2, 0, 1, 2, 1, 2, 1, 2, 0, 1, 2, 2, 0, 2, 1, 0, 2, 0, 1, 2, 0, 1, 1, 1, 1, 2, 2, 2, 1, 1, 0, 2, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 2, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 2, 1, 2, 0, 2, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 2, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 2, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1]


In [ ]:
kmeans = KMeans(n_clusters = 3, random_state = 42)
l3 = kmeans.fit_predict(X3).tolist()
print("l3 = " + str(l3))

l3 = [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 1, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, 1, 2, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 2, 1, 2, 1, 2, 2, 1, 2, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 2, 2, 2, 1, 2, 2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 2, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 2, 1, 1, 0, 1, 0, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 0, 1, 2, 0, 0, 0, 0, 1, 1, 1, 1, 0, 2, 1, 1, 0, 1, 0, 0, 2, 0, 0, 2, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 2, 1, 0, 1, 1, 1, 0, 0, 2, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]


In [ ]:
kmeans = KMeans(n_clusters = 3, random_state = 42)
l4 = kmeans.fit_predict(X4).tolist()
print("l4 = " + str(l4))

l4 = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 2, 1, 2, 1, 2, 2, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 2, 0, 1, 0, 0, 0, 0, 2, 1, 1, 1, 0, 0, 2, 1, 0, 0, 1, 0, 0, 2, 0, 1, 1, 2, 1, 0, 2, 1, 2, 1, 1, 2, 0, 0, 0, 0, 0, 0, 1, 1, 0, 2, 1, 2, 2, 2, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 2, 0, 2, 0, 1, 0, 0, 2, 0, 0, 2, 2, 2, 0, 0, 2, 0, 0, 0, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 2, 1, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0]


In [ ]:
kmeans = KMeans(n_clusters = 3, random_state = 42)
l5 = kmeans.fit_predict(X5).tolist()
print("l5 = " + str(l5))

l5 = [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 0, 2, 2, 1, 2, 2, 2, 2, 2, 0, 2, 2, 2, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 1, 2, 2, 1, 2, 2, 2, 2, 2, 0, 0, 2, 2, 0, 2, 0, 2, 2, 2, 0, 2, 2, 0, 2, 2, 0, 1, 0, 0, 1, 2, 0, 2, 0, 0, 2, 2, 2, 0, 0, 2, 2, 1, 0, 2, 2, 2, 2, 2, 1, 0, 0, 2, 0, 2, 0, 1, 2, 1, 0, 2, 1, 2, 2, 2, 2, 2, 2, 2, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1]


In [ ]:
kmeans = KMeans(n_clusters = 3, random_state = 42)
l6 = kmeans.fit_predict(X6).tolist()
print("l6 = " + str(l6))

l6 = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 2, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 2, 0, 2, 2, 0, 1, 0, 0, 0, 2, 0, 2, 0, 0, 2, 2, 2, 0, 2, 2, 1, 0, 0, 2, 2, 1, 2, 2, 1, 0, 0, 1, 0, 2, 1, 1, 1, 1, 0, 2, 1, 2, 2, 2, 2, 2, 2, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 2, 0, 2, 0, 2, 0, 0, 2, 0, 2, 2, 2, 0, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 2, 0, 2, 2, 2, 2, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 0, 2, 2, 0, 2, 2, 2, 2, 0, 0, 0, 0, 0, 2, 2, 2, 2, 0, 0, 2, 2, 0, 0, 2, 0, 0, 0, 0, 0, 0]


In [ ]:
kmeans = KMeans(n_clusters = 3, random_state = 42)
l7 = kmeans.fit_predict(X7).tolist()
print("l7 = " + str(l7))

l7 = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 2, 1, 2, 2, 0, 0, 0, 0, 2, 1, 0, 2, 0, 0, 0, 1, 0, 0, 2, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 2, 0, 1, 2, 1, 2, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 0, 0, 1, 1, 2, 1, 0, 0, 2, 1, 2, 2, 1, 2, 0, 1, 2, 1, 1, 1, 1, 1, 1, 1, 0, 0, 2, 0, 2, 2, 2, 0, 0, 2, 1, 0, 2, 1, 1, 1, 2, 1, 1, 2, 1, 2, 1, 2, 1, 1, 1, 2, 0, 2, 1, 0, 1, 1, 2, 1, 0, 1, 2, 0, 2, 1, 1, 2, 1, 1, 2, 1, 2, 1, 1, 1, 1, 2, 1, 0, 2, 2, 2, 1, 2, 2, 1, 0, 1, 1, 1, 1, 2, 1, 1, 2, 2, 1, 2, 2, 1, 1, 1, 1, 2, 0, 1, 1, 2, 1, 1, 0, 1, 0, 2, 1, 2]


In [ ]:
kmeans = KMeans(n_clusters = 3, random_state = 42)
l8 = kmeans.fit_predict(X8).tolist()
print("l8 = " + str(l8))

l8 = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 2, 1, 2, 1, 1, 1, 2, 1, 1, 1, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 0, 1, 1, 2, 1, 2, 1, 1, 1, 2, 1, 1, 2, 1, 1, 2, 2, 2, 2, 0, 1, 2, 1, 2, 2, 1, 1, 1, 0, 2, 1, 1, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 1, 2, 1, 2, 0, 1, 2, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 0, 2, 2, 2, 0, 2, 0, 2, 2, 0, 2, 0, 0, 0, 2, 2, 2, 2, 0, 0, 2, 0, 2, 0, 2, 2, 2, 0, 2, 0, 2, 2, 2, 0, 0, 2, 2, 2, 0, 2, 2, 0, 2, 0, 0, 2, 0, 2, 0, 2, 2, 2, 2, 0, 2, 2, 0, 0, 0, 2, 0, 0, 2, 2, 2, 2, 0, 2, 0, 2, 2, 0, 0, 0, 0, 0, 0, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 0, 0, 2, 2, 0, 0]


In [ ]:
kmeans = KMeans(n_clusters = 3, random_state = 42)
l9 = kmeans.fit_predict(X9).tolist()
print("l9 = " + str(l9))

l9 = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 0, 1, 1, 1, 2, 1, 1, 1, 2, 1, 2, 2, 1, 1, 2, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 2, 1, 2, 1, 2, 2, 1, 1, 1, 1, 2, 1, 1, 2, 2, 1, 1, 1, 1, 2, 2, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 2, 2, 2, 2, 1, 2, 1, 2, 0, 1, 2, 2, 2, 1, 1, 2, 2, 2, 2, 1, 1, 0, 2, 1, 1, 1, 1, 2, 0, 2, 2, 2, 2, 1, 2, 0, 2, 0, 1, 1, 2, 1, 1, 1, 1, 2, 2, 2, 2, 1, 0, 2, 0, 0, 0, 1, 1, 0, 2, 2, 0, 2, 2, 2, 2, 1, 2, 0, 1, 0, 1, 0, 1, 2, 2, 0, 1, 0, 2, 1, 1, 0, 0, 2, 1, 2, 0, 1, 0, 2, 2, 0, 2, 2, 0, 1, 0, 2, 2, 1, 2, 0, 2, 2, 0, 0, 0, 1, 0, 0, 2, 2, 2, 2, 2, 2, 0, 1, 2, 0, 2, 2, 2, 0, 0, 2, 2, 1, 0, 1, 2, 2, 0, 2, 1, 2, 2, 1, 2, 2, 0]


In [ ]:
kmeans = KMeans(n_clusters = 3, random_state = 42)
l10 = kmeans.fit_predict(X10).tolist()
print("l10 = " + str(l10))

l10 = [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 0, 2, 1, 2, 1, 0, 1, 0, 2, 0, 2, 0, 0, 2, 2, 2, 2, 0, 2, 2, 0, 2, 2, 2, 2, 2, 2, 0, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 0, 0, 1, 2, 2, 2, 1, 1, 0, 2, 0, 0, 1, 1, 0, 0, 2, 1, 2, 1, 2, 0, 1, 0, 2, 0, 2, 1, 0, 2, 0, 1, 2, 0, 1, 1, 1, 1, 2, 2, 2, 0, 1, 0, 2, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 2, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1]


In [ ]:
final_array = []
final_array.append(l1)
final_array.append(l2)
final_array.append(l3)
final_array.append(l4)
final_array.append(l5)
final_array.append(l6)
final_array.append(l7)
final_array.append(l8)
final_array.append(l9)
final_array.append(l10)

print(final_array)

[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 2, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 2, 1, 1, 0, 0, 1, 1, 2, 1, 1, 0, 2, 1, 0, 2, 0, 2, 0, 1, 2, 1, 1, 1, 0, 1, 1, 0, 1, 0, 2, 1, 2, 2, 2, 0, 0, 2, 1, 1, 2, 1, 1, 1, 2, 1, 1, 2, 1, 2, 1, 2, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 2, 1, 2, 1, 1, 2, 1, 1, 2, 1, 2, 1, 1, 1, 1, 2, 1, 1, 2, 2, 2, 1, 2, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 2, 2, 1, 1, 1, 1, 2, 0, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 2], [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 

# Cluster Relabelling and Get a final ensamble cluster solution 

# Input

In [ ]:
array_2d = final_array # Solution sets

# ARI matrix

In [ ]:
ARI_matrix = []
def fact(num):
  f = 1
  for i in range(1, num + 1):
    f = f * i
  
  return f

def comb(n,r):
  com = fact(n) / (fact(r) * fact(n-r))
  return com

def ARI(X,Y):
  c = 0
  ARI_value = 0
  for i in range(len(X)-1):
    for j in range(i,len(X)-1):
      if((X[i] == X[j+1]) &  (Y[i] == Y[j+1]) ):
        c = c + 1
      if((X[i] != X[j+1]) &  (Y[i] != Y[j+1]) ):
        c = c + 1

  ARI_value   =   c / comb(len(X),2)
  return ARI_value
  

Choose a reference cluster by ARI marix (Most similar)

In [ ]:
avg = []
total = 0

for j in range(len(array_2d)):
    total = 0
    for i in range(len(array_2d)):
        total = total +  ARI(array_2d[j], array_2d[i])
        print(ARI(array_2d[j], array_2d[i]),  end ="      ")
    print('\n')
    avg.append(total/len(array_2d[0])) 
print("Avarge values of each row ", avg)

1.0      0.7940471563674051      0.6375178131882369      0.8074232413525068      0.7693354061406918      0.7521699702033943      0.8230340717709548      0.7132400570022024      0.6996696463272445      0.739214924212981      

0.7940471563674051      1.0      0.7140497473766032      0.8550654229822516      0.7834887938852183      0.6940989765513668      0.7063414950123073      0.7478624174115818      0.6373882627283327      0.8475514963078119      

0.6375178131882369      0.7140497473766032      1.0      0.6967871485943775      0.6108304184479855      0.6546184738955824      0.5978753724575723      0.6053892991320119      0.5397396035755927      0.7154424148205726      

0.8074232413525068      0.8550654229822516      0.6967871485943775      1.0      0.7182277497085114      0.6941961393962949      0.7712138878093017      0.6888197953102734      0.6527076046119964      0.8592434253141599      

0.7693354061406918      0.7834887938852183      0.6108304184479855      0.7182277497085114   

In [ ]:
initial = -99
index = -99
for i in range(len(avg)):
  if(avg[i] > initial):
    initial = avg[i]
    index = i

print("Reference cluster number is = " + str(index))
print("Reference clusteris = ", array_2d[index] )

Reference cluster number is = 1
Reference clusteris =  [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 1, 0, 2, 2, 0, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 1, 1, 1, 2, 0, 1, 1, 2, 1, 1, 1, 2, 2, 1, 2, 1, 2, 0, 1, 2, 1, 2, 1, 2, 0, 1, 2, 2, 0, 2, 1, 0, 2, 0, 1, 2, 0, 1, 1, 1, 1, 2, 2, 2, 1, 1, 0, 2, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 2, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 2, 1, 2, 0, 2, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 2, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 2, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1]


# Relabaling

In [ ]:
def majority(a):
  mode = max(a, key = a.count)
  a = [mode] * len(a)
  return a

In [ ]:
def relab(list1, list2):
  list3 = list2.copy()
  p = 0

  for i in range(len(list2)):
    if (list2[i] != list2[p]):
      list3[p : i] = majority(list1[p : i])
      p = i
    if (i == len(list2)-1):
      list3[p : ] = majority(list1[p :])  
      p = i


  #print("Reference Dataset: " + str(list1))
  #print("Given     Dataset: " + str(list2))
  list2 = list3
  ARI_matrix.append(list2)
  print("Modified  Dataset: " + str(list2))

In [ ]:
for k in range(len(array_2d)):
  relab(array_2d[index], array_2d[k])


Modified  Dataset: [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 0, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 2, 0, 2, 1, 0, 2, 0, 1, 2, 0, 1, 1, 1, 1, 2, 2, 2, 1, 1, 0, 2, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 2, 2, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 2, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1]
Modified  Dataset: [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 

In [ ]:
label_array = ARI_matrix.copy()
print(label_array)

[[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 0, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 2, 0, 2, 1, 0, 2, 0, 1, 2, 0, 1, 1, 1, 1, 2, 2, 2, 1, 1, 0, 2, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 2, 2, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 2, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1], [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 

In [ ]:
p1 = np.array(label_array[0])
p2 = np.array(label_array[1])
p3 = np.array(label_array[2])
p4 = np.array(label_array[3])
p5 = np.array(label_array[4])
p6 = np.array(label_array[5])
p7 = np.array(label_array[6])
p8 = np.array(label_array[7])
p9 = np.array(label_array[8])
p10 = np.array(label_array[9])

In [ ]:
distance_array = []

for j in range(len(p1)):
  b = []
  for k in range(len(p1)):
    count = 0

    if(p1[j] == p1[k]):
      count = count + 1
    if(p2[j] == p2[k]):
      count = count + 1
    if(p3[j] == p3[k]):
      count = count + 1
    if(p4[j] == p4[k]):
      count = count + 1
    if(p5[j] == p5[k]):
      count = count + 1
    if(p6[j] == p6[k]):
      count = count + 1
    if(p7[j] == p7[k]):
      count = count + 1
    if(p8[j] == p8[k]):
      count = count + 1
    if(p9[j] == p9[k]):
      count = count + 1
    if(p10[j] == p10[k]):
      count = count + 1

    dist = 1 - count * 0.1
    b.append(dist)
  
  distance_array.append(b)

print(np.array(distance_array))

[[0. 0. 0. ... 1. 1. 1.]
 [0. 0. 0. ... 1. 1. 1.]
 [0. 0. 0. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 0. 0. 0.]
 [1. 1. 1. ... 0. 0. 0.]
 [1. 1. 1. ... 0. 0. 0.]]


In [ ]:
print(distance_array[76])

[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.8, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.9, 0.09999999999999998, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.7, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.6, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.29999999999999993, 0.8, 0.0, 0.0, 0.9, 0.09999999999999998, 0.0, 0.0, 0.0, 0.0, 0.0, 0.6, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.5, 0.09999999999999998, 0.09999999999999998, 1.0, 1.0, 1.0, 0.3999999999999999, 0.9, 1.0, 1.0, 0.5, 0.9, 1.0, 0.6, 0.09999999999999998, 0.09999999999999998, 0.6, 0.29999999999999993, 0.8, 0.5, 1.0, 1.0, 0.29999999999999993, 0.5, 0.19999999999999996, 0.7, 0.3999999999999999, 1.0, 0.8, 0.3999999999999999, 0.0, 0.8, 0.0, 0.9, 1.0, 0.09999999999999998, 0.9, 1.0, 0.19999999999999996, 1.0, 1.0, 1.0, 1.0, 1.

# Implementation Ensamble Voting approch

In [ ]:
number_set = [0] * (len(ARI_matrix[0]) + 1)
print(number_set)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [ ]:
column_values = ['X'] * len(ARI_matrix[0])

In [ ]:
thres = float(input("Enter voting threshold:"))

Enter voting threshold:0.6


In [ ]:
number_set = [0] * (len(ARI_matrix[0]) + 1)

for i in range(len(ARI_matrix[0])):
  for j in range(len(ARI_matrix)):
    number_set[ARI_matrix[j][i]] = (number_set[ARI_matrix[j][i]]  + 1)
  
  max_num = -9
  index_num = -9
  for k in range(len(number_set)):
    if(number_set[k] > max_num):
      max_num = number_set[k]
      index_num = k
  if(max_num > (len(ARI_matrix) * thres)):
    column_values[i] = index_num

  number_set = [0] * (len(ARI_matrix[0]) + 1)  

  

# Voting Result with some missing values

In [ ]:
print("Final ouput : ",column_values)  

Final ouput :  [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 'X', 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 0, 2, 2, 2, 2, 2, 2, 'X', 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 'X', 2, 2, 1, 1, 1, 'X', 0, 1, 1, 'X', 1, 1, 'X', 2, 2, 'X', 2, 1, 'X', 0, 1, 2, 'X', 2, 1, 'X', 0, 1, 'X', 2, 0, 2, 1, 0, 2, 0, 1, 2, 0, 1, 1, 1, 1, 'X', 'X', 2, 1, 1, 0, 2, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 'X', 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 'X', 1, 'X', 0, 2, 'X', 0, 0, 0, 1, 1, 'X', 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 'X', 1, 1, 1, 1, 0, 2, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1]


In [ ]:
len(column_values)

249

# **Using Distance Method**

In [ ]:
label_list = []
missing_list = []

for i in range(len(column_values)):
  if(column_values[i] == 'X'):
    label_list.append(int(999))
    missing_list.append(i)
  else:
    label_list.append(int(column_values[i]))

print(label_list)
print(missing_list)

[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 999, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 0, 2, 2, 2, 2, 2, 2, 999, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 999, 2, 2, 1, 1, 1, 999, 0, 1, 1, 999, 1, 1, 999, 2, 2, 999, 2, 1, 999, 0, 1, 2, 999, 2, 1, 999, 0, 1, 999, 2, 0, 2, 1, 0, 2, 0, 1, 2, 0, 1, 1, 1, 1, 999, 999, 2, 1, 1, 0, 2, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 999, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 999, 1, 999, 0, 2, 999, 0, 0, 0, 1, 1, 999, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 999, 1, 1, 1, 1, 0, 2, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1]
[79, 97, 109, 115, 119, 122, 125, 128, 132, 135, 138, 153, 154, 190, 206, 208, 211, 217, 231]


In [ ]:
def sort(list1, lablist):  
    # Outer loop for traverse the entire list  
    for i in range(0,len(list1)-1):  
        for j in range(len(list1)-1):  
            if(list1[j]>list1[j+1]):  
                temp = list1[j]  
                list1[j] = list1[j+1]  
                list1[j+1] = temp
                
                temp2 = lablist[j]
                lablist[j] = lablist[j+1]
                lablist[j+1] = temp2

    return list1, lablist

In [ ]:
from collections import Counter

obtained_labels = []
for i in missing_list:
  sorted_dist, lab = sort(distance_array[i], label_list)

  obtained_labels.append(Counter(lab[:7]).most_common(1)[0][0])

print(obtained_labels)

[0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 1, 2, 1, 2, 1, 2]


In [ ]:
new_labels = list(obtained_labels.copy())
our_method_output = list(column_values)
for i in range(len(column_values)):
    if(column_values[i] == 'X'):
      our_method_output[i] = new_labels[0]
      new_labels.pop(0)      

print(column_values)
print(our_method_output)

[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 'X', 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 0, 2, 2, 2, 2, 2, 2, 'X', 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 'X', 2, 2, 1, 1, 1, 'X', 0, 1, 1, 'X', 1, 1, 'X', 2, 2, 'X', 2, 1, 'X', 0, 1, 2, 'X', 2, 1, 'X', 0, 1, 'X', 2, 0, 2, 1, 0, 2, 0, 1, 2, 0, 1, 1, 1, 1, 'X', 'X', 2, 1, 1, 0, 2, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 'X', 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 'X', 1, 'X', 0, 2, 'X', 0, 0, 0, 1, 1, 'X', 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 'X', 1, 1, 1, 1, 0, 2, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1]
[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 

# **Implementing Naive Bayes Classifier**

In [ ]:
array = np.transpose(ARI_matrix)

In [ ]:
len(array)

249

In [ ]:
train_X = []
test_X = []
train_y = []

for i in range(len(column_values)):
  if (column_values[i] == 'X'):
    test_X.append(array[i].tolist())
  else:
    train_X.append(array[i].tolist())
    train_y.append(column_values[i])

In [ ]:
print(train_X)
print(train_y)
print(test_X)

[[2, 2, 2, 2, 2, 2, 2, 2, 2, 2], [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], [2, 2, 

In [ ]:
from sklearn.naive_bayes import GaussianNB
 
#Calling the Class
naive_bayes = GaussianNB()
 
#Fitting the data to the classifier
naive_bayes.fit(train_X , train_y)
 
#Predict on test data
y_predicted = naive_bayes.predict(test_X)

In [ ]:
print(y_predicted)

[2 0 2 2 1 1 1 2 1 2 2 2 2 0 2 1 2 1 1]


In [ ]:
new_labels = list(y_predicted.copy())
naive_output = list(column_values)
for i in range(len(column_values)):
    if(column_values[i] == 'X'):
      naive_output[i] = new_labels[0]
      new_labels.pop(0)      

print(column_values)
print(naive_output)

[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 'X', 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 0, 2, 2, 2, 2, 2, 2, 'X', 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 'X', 2, 2, 1, 1, 1, 'X', 0, 1, 1, 'X', 1, 1, 'X', 2, 2, 'X', 2, 1, 'X', 0, 1, 2, 'X', 2, 1, 'X', 0, 1, 'X', 2, 0, 2, 1, 0, 2, 0, 1, 2, 0, 1, 1, 1, 1, 'X', 'X', 2, 1, 1, 0, 2, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 'X', 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 'X', 1, 'X', 0, 2, 'X', 0, 0, 0, 1, 1, 'X', 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 'X', 1, 1, 1, 1, 0, 2, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1]
[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 

# KNN implementation for filling missing values

In [ ]:
data['Class'] = column_values

In [ ]:
data = data.drop(["User Id"], axis = 1)

In [ ]:
train_df = data[data['Class'] != 'X']
train_df 

Sports  Religious  Nature  Theatre  Shopping  Picnic Class
0         2         77      79       69        68      95     2
1         2         62      76       76        69      68     2
2         2         50      97       87        50      75     2
3         2         68      77       95        76      61     2
4         2         98      54       59        95      86     2
..      ...        ...     ...      ...       ...     ...   ...
244      18        139     148      129       129     168     1
245      22        114     228      104        84     168     1
246      20        124     178      104       158     174     1
247      20        133     149      139       144     213     1
248      20        143     149      139       159     143     1

[230 rows x 7 columns]

In [ ]:
test_df = data[data['Class'] == 'X']
test_df

Sports  Religious  Nature  Theatre  Shopping  Picnic Class
79        6        124      59       84       143      88     X
97        6        148      64       74       138     128     X
109      12        123     124      109       114     168     X
115      12        133     104      119       129     133     X
119      12         94     137      148       113     100     X
122      14         81     173      143        79     122     X
125      14        138     119      119       124     158     X
128      12         84     150      128       104     102     X
132      12         79     183      133        70     113     X
135      12        109     135      158       123      92     X
138      12        128     124      114       111     126     X
153      12        104     130      178       118      92     X
154      10         99     123      153       128     103     X
190      20        162      94      144       198     135     X
206      16        132      94      178       109     120     X
208      16        137     104      173       109     130     X
211      22        114     228      119        99     168     X
217      18        198      64       89       203     153     X
231      18        188      74      109       213     168     X

In [ ]:
X_train = np.array(train_df.drop(["Class"], axis = 1))
Y_train = np.array(train_df["Class"]).astype('int')
test_X = np.array(test_df.drop(["Class"], axis = 1))

In [ ]:
knn = KNeighborsClassifier().fit(X_train, Y_train)
pred = knn.predict(test_X)
print(pred)

[2 0 1 1 2 1 1 2 1 2 1 2 2 0 2 2 1 0 0]


In [ ]:
new_labels = list(pred.copy())
result_output = list(column_values)
for i in range(len(column_values)):
    if(column_values[i] == 'X'):
      result_output[i] = new_labels[0]
      new_labels.pop(0)      

print(column_values)
print(result_output)

[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 'X', 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 0, 2, 2, 2, 2, 2, 2, 'X', 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 'X', 2, 2, 1, 1, 1, 'X', 0, 1, 1, 'X', 1, 1, 'X', 2, 2, 'X', 2, 1, 'X', 0, 1, 2, 'X', 2, 1, 'X', 0, 1, 'X', 2, 0, 2, 1, 0, 2, 0, 1, 2, 0, 1, 1, 1, 1, 'X', 'X', 2, 1, 1, 0, 2, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 'X', 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 'X', 1, 'X', 0, 2, 'X', 0, 0, 0, 1, 1, 'X', 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 'X', 1, 1, 1, 1, 0, 2, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1]
[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 


#**Testing cluster quality**

In [ ]:
from sklearn.metrics import davies_bouldin_score

print(davies_bouldin_score(X, our_method_output))

1.119344938973205


In [ ]:
pip install --upgrade s-dbw

In [ ]:
from s_dbw import S_Dbw

print(S_Dbw(X, our_method_output, centers_id=None, method='Tong', alg_noise='bind', centr='mean', nearest_centr=True, metric='euclidean'))

0.6941751662904749


In [ ]:
from sklearn.metrics import silhouette_score

print(silhouette_score(X, our_method_output))

0.3107090553828165


In [ ]:
from sklearn.metrics import calinski_harabasz_score

print(calinski_harabasz_score(X, our_method_output))

114.6859181150053


In [ ]:
print(davies_bouldin_score(X, naive_output))

1.0987001518632789


In [ ]:
print(S_Dbw(X, naive_output, centers_id=None, method='Tong', alg_noise='bind', centr='mean', nearest_centr=True, metric='euclidean'))

0.6827315755490202


In [ ]:
print(silhouette_score(X, naive_output))

0.3244801724061567


In [ ]:
print(calinski_harabasz_score(X, naive_output))

123.57646939891828


In [ ]:
print(davies_bouldin_score(X, result_output))

1.0388694269466965


In [ ]:
print(S_Dbw(X, result_output, centers_id=None, method='Tong', alg_noise='bind', centr='mean', nearest_centr=True, metric='euclidean'))

0.6628524713723817


In [ ]:
print(silhouette_score(X, result_output))

0.34693676098222237


In [ ]:
print(calinski_harabasz_score(X, result_output))

144.2030394533163


In [ ]:
!pip install ClusterEnsembles

     |████████████████████████████████| 297 kB 5.1 MB/s 
     |████████████████████████████████| 38.1 MB 1.3 MB/s 
     |████████████████████████████████| 1.1 MB 35.2 MB/s 
  Created wheel for pymetis: filename=PyMetis-2020.1-cp37-cp37m-linux_x86_64.whl size=276538 sha256=bb5a726bbfaab83010d0ae3eb0e3927aced0581d5ca6ca23f4a68a063e202152
  Stored in directory: /root/.cache/pip/wheels/fc/6a/69/a4296ff80443cd9b3876eaea9bd8dfeed30cc8443708848097
Successfully built pymetis
  Attempting uninstall: scipy
    Found existing installation: scipy 1.4.1
    Uninstalling scipy-1.4.1:
      Successfully uninstalled scipy-1.4.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
albumentations 0.1.12 requires imgaug<0.2.7,>=0.2.5, but you have imgaug 0.2.9 which is incompatible.


In [ ]:
import ClusterEnsembles as CE

In [ ]:
labels = np.array([l1, l2, l3, l4, l5, l6, l7, l8, l9, l10])

In [ ]:
celabel = CE.cluster_ensembles(labels, solver='cspa' )

celabel

print(davies_bouldin_score(X, celabel))
print(S_Dbw(X, celabel, centers_id=None, method='Tong', alg_noise='bind', centr='mean', nearest_centr=True, metric='euclidean'))
print(silhouette_score(X, celabel))
print(calinski_harabasz_score(X, celabel))

1.3266263354726957
0.7139029870809324
0.27351529797499324
111.44172024269727


In [ ]:
celabel2 = CE.cluster_ensembles(labels, solver='hgpa' )

celabel2

print(davies_bouldin_score(X, celabel2))
print(S_Dbw(X, celabel2, centers_id=None, method='Tong', alg_noise='bind', centr='mean', nearest_centr=True, metric='euclidean'))
print(silhouette_score(X, celabel2))
print(calinski_harabasz_score(X, celabel2))

1.393022044745023
0.7239367077210216
0.23856023825159708
102.20996009997266


In [ ]:
celabel3 = CE.cluster_ensembles(labels, solver='mcla' )

celabel3

print(davies_bouldin_score(X, celabel3))
print(S_Dbw(X, celabel3, centers_id=None, method='Tong', alg_noise='bind', centr='mean', nearest_centr=True, metric='euclidean'))
print(silhouette_score(X, celabel3))
print(calinski_harabasz_score(X, celabel3))

1.0984191764565352
0.6854816332023149
0.3314257266449292
139.87632368385258


In [ ]:
celabel4 = CE.cluster_ensembles(labels, solver='hbgf' )

celabel4

print(davies_bouldin_score(X, celabel4))
print(S_Dbw(X, celabel4, centers_id=None, method='Tong', alg_noise='bind', centr='mean', nearest_centr=True, metric='euclidean'))
print(silhouette_score(X, celabel4))
print(calinski_harabasz_score(X, celabel4))

1.445369199645162
0.7306310357840183
0.23798258171913686
97.90485064848227


In [ ]:
celabel5 = CE.cluster_ensembles(labels, solver='nmf' )

celabel5

print(davies_bouldin_score(X, celabel5))
print(S_Dbw(X, celabel5, centers_id=None, method='Tong', alg_noise='bind', centr='mean', nearest_centr=True, metric='euclidean'))
print(silhouette_score(X, celabel5))
print(calinski_harabasz_score(X, celabel5))

1.0741861244319293
0.6795650148156112
0.33712263921324187
143.65017140785366
